### ISSUE TITLE
Trouble understanding the delta update schema

### ISSUE THREAD

**Issue by ph1l** [SignalK/specification#285]
So `updates` is an array of objects and it is required to contain the property `values`. but this next thing is structured weird, so I'd like to clarify:

```
        "not": {
          "allOf": [{
            "required": ["source"]
          }, {
            "required": ["$source"]
          }]
        },
```
Does that mean that you can't have both, but either or none is fine?

in context: https://github.com/SignalK/specification/blob/master/schemas/delta.json#L23-L29

ALSO: If I'm streaming delta messages, why would I receive subscribe, unsubscribe, get, list, or put messages from the server?

**Comment by tkurki** [comment]
>Does that mean that you can't have both, but either or none is fine?

Yes. The idea is that 
- source is optional - for example a SK producing sensor talking to a SK server can send deltas without source, since it is sort of irrelevant to the sender - it only knows about itself and the server should fill in relevant information about the sensor to the deltas, especially if the server is multiplexing data from multiple sources
- source is either the `source` object with relevant properties or the `$source` property, which is a pointer to possibly more data under /sources and a unique id at the same time, encoding 

See also https://github.com/SignalK/specification/pull/238

especially 

https://github.com/SignalK/specification/pull/238#issuecomment-237996702


Hmm, I wonder where in the documentation this should be included?

Did that answer your question?

**Comment by ph1l** [comment]
That answers the main question.

Should I open another issue for the ALSO part? Basically, I'm confused as to why delta.json spec contains all the other stuff (subscribe, unsubscribe, get, list, and put). Aren't those messages that I, as a client, would send to the server?

**Comment by tkurki** [comment]
_subscribe, unsubscribe, get, list, and put_ are for replicating HTTP api functionality over ws. 

They should be separate as they are not directly related to deltas, see https://github.com/SignalK/specification/pull/239.

Ping @rob42

**Comment by ph1l** [comment]
that's what I assumed, thanks!
-- 
Sent from my Blackphone with K-9 Mail. Please excuse my brevity.

**Comment by ph1l** [comment]
should the issue be closed if the specification is not clarified?

other attempting to develop clients against the spec may have problems as well.

best,

@ph1l
--

**Comment by tkurki** [comment]
Do you think there is something not covered in #239?

**Comment by ph1l** [comment]
sorry not able to check, is #239 still open pending updates to the
docs?  I'm just trying to say maybe they could be improved. Your call.
just trying to help out...
