### ISSUE TITLE
metadata: timeout appears to have a dual purpose

### ISSUE THREAD

**Issue by bkp7** [SignalK/specification#410]
Timeout is described in the schema as "The timeout after which this data is invalid", but the documentation says it can also be used as the interval between polling for a new value. These seem to be 2 distinctly different requirements being rolled into one value. What value is to be used for invalid data if the gauge is polling. It must be greater than the polling interval to allow time for a response to its poll? As an example a fuel gauge might poll once a second, but due to the nature of the measurement that could be valid for many seconds or even minutes before the gauge has to cease showing any value.

Possible solution: ensure the documentation is consistent with the schema. Add a new property of pollingInterval and some explanation against both.

**Comment by bkp7** [comment]
The section is [here](https://github.com/SignalK/specification/blob/c375cd7e4c50200a1380eb688c6409bec2e05d1a/gitbook-docs/data_model_metadata.md#metadata-for-a-data-value)

I agree with your comments on polling. Maybe we just need a re-wording here. What you describe could well have been what the author was getting at, but I didn't read it that way.

How about:

'The `timeout` property tells the consumer how long it should display a value for before it must be refreshed. If a new value is not received the consumer must assume the source has failed and display an appropriate error indication. If the consumer is using polling to read the value the `timeout` may be used as a basis for deciding on a polling interval. This value is specified in seconds .......'

**Comment by tkurki** [comment]
You are dictating client behavior and thinking just about displaying the latest value.

 _The timeout property tells the consumer how long it should consider the value valid_ would be more accurate.

It is really up to the consumer (and possibly the human user who configures the consumer) how it chooses to deal with the situation: flash the display, just clear the display, start drawing a dashed instead of a solid line in the graph, stop drawing the line, change the vessel marker on the map, remove the value from the latest values cache....

**Comment by tkurki** [comment]
...and I think we should just remove the reference to polling. That is up to the client.
